"""Votes cascading delete

Revision ID: 0605bd1a7d3a
Revises: 734e1194a936
Create Date: 2025-04-24 19:28:19.832526

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '0605bd1a7d3a'
down_revision = '734e1194a936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('votes_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('votes_post_id_fkey', 'blog_posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
