"""Fix comments cascading delete

Revision ID: 27b65909d60b
Revises: 0605bd1a7d3a
Create Date: 2025-04-24 19:47:33.624045

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '27b65909d60b'
down_revision = '0605bd1a7d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_post_id_fkey', 'blog_posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
