"""Add reset_token and reset_token_expiry to User model

Revision ID: 573bc4d6a83c
Revises: 721d86f89554
Create Date: 2025-10-19 20:34:53.301465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573bc4d6a83c'
down_revision = '721d86f89554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
