"""add 2FA auth to User model

Revision ID: 6b2e7765d580
Revises: f6c517f0734e
Create Date: 2025-12-18 10:41:51.853209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2e7765d580'
down_revision = 'f6c517f0734e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twofa_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('twofa_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('twofa_enabled', sa.Boolean(), nullable=True))

    # Step 2: Set default value for existing rows (False for all users)
    op.execute('UPDATE users SET twofa_enabled = FALSE WHERE twofa_enabled IS NULL')

    # Step 3: Make column non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('twofa_enabled', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('twofa_enabled')
        batch_op.drop_column('twofa_expires_at')
        batch_op.drop_column('twofa_code')

    # ### end Alembic commands ###
