"""Add login tracking and security fields to User model

Revision ID: f6c517f0734e
Revises: 573bc4d6a83c
Create Date: 2025-12-17 08:27:49.716339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c517f0734e'
down_revision = '573bc4d6a83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_login_browser', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login_device', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rate_limit_violations', sa.Integer(), nullable=True))
        batch_op.alter_column('reset_token',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_unique_constraint(None, ['reset_token'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('reset_token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('rate_limit_violations')
        batch_op.drop_column('password_reset_count')
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('last_login_device')
        batch_op.drop_column('last_login_browser')
        batch_op.drop_column('last_login_location')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('last_login')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('token_version')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
